import './globals.css'
import { livvic } from './font'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${livvic.variable}`}>
      <body className="overflow-x-hidden font-livvic bg-primaryGreen text-white">{children}</body>
    </html>
  )
}
