import './globals.css'
import { livvic } from './font'
import { Navbar, Footer } from '@/components/shared'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${livvic.variable}`}>
      <body className="overflow-x-hidden font-livvic bg-primaryGreen text-white">
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
